// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class DataLabelingDBContext : DbContext
{
    public DataLabelingDBContext()
    {
    }

    public DataLabelingDBContext(DbContextOptions<DataLabelingDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<Annotation> Annotations { get; set; }

    public virtual DbSet<DataItem> DataItems { get; set; }

    public virtual DbSet<DataItemAssignment> DataItemAssignments { get; set; }

    public virtual DbSet<Dataset> Datasets { get; set; }

    public virtual DbSet<DatasetAssignment> DatasetAssignments { get; set; }

    public virtual DbSet<ExportItem> ExportItems { get; set; }

    public virtual DbSet<ExportJob> ExportJobs { get; set; }

    public virtual DbSet<FinalResult> FinalResults { get; set; }

    public virtual DbSet<Label> Labels { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectMember> ProjectMembers { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<PasswordResetToken> PasswordResetTokens { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .UseSqlServer(GetConnectionString("DefaultConnection"), b => b.MigrationsAssembly("DataLabeling.Domain"))
        .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=MSI;Initial Catalog=DataLabelingDB;Persist Security Info=True;User ID=sa;Password=12345");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ActivityLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__activity__3213E83F1C38B9E9");

            entity.ToTable("activity_logs");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("action");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.EntityId).HasColumnName("entity_id");
            entity.Property(e => e.EntityType)
                .HasMaxLength(50)
                .HasColumnName("entity_type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__activity___user___02084FDA");
        });

        modelBuilder.Entity<Annotation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__annotati__3213E83F99346635");

            entity.ToTable("annotations");

            entity.HasIndex(e => new { e.DataItemId, e.UserId }, "uq_annotation").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DataItemId).HasColumnName("data_item_id");
            entity.Property(e => e.LabelValue)
                .IsRequired()
                .HasColumnName("label_value");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("submitted")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.DataItem).WithMany(p => p.Annotations)
                .HasForeignKey(d => d.DataItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__annotatio__data___66603565");

            entity.HasOne(d => d.User).WithMany(p => p.Annotations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__annotatio__user___6754599E");
        });

        modelBuilder.Entity<DataItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__data_ite__3213E83FBDA3945B");

            entity.ToTable("data_items");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DatasetId).HasColumnName("dataset_id");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("new")
                .HasColumnName("status");

            entity.HasOne(d => d.Dataset).WithMany(p => p.DataItems)
                .HasForeignKey(d => d.DatasetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__data_item__datas__4F7CD00D");
        });

        modelBuilder.Entity<DataItemAssignment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__data_ite__3213E83FA4E4CB8A");

            entity.ToTable("data_item_assignments");

            entity.HasIndex(e => new { e.DataItemId, e.UserId }, "uq_dataitem_user").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("assigned_at");
            entity.Property(e => e.DataItemId).HasColumnName("data_item_id");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("assigned")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.DataItem).WithMany(p => p.DataItemAssignments)
                .HasForeignKey(d => d.DataItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__data_item__data___5BE2A6F2");

            entity.HasOne(d => d.User).WithMany(p => p.DataItemAssignments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__data_item__user___5CD6CB2B");
        });

        modelBuilder.Entity<Dataset>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__datasets__3213E83FC17920A2");

            entity.ToTable("datasets");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("active")
                .HasColumnName("status");

            entity.HasOne(d => d.Project).WithMany(p => p.Datasets)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__datasets__projec__4AB81AF0");
        });

        modelBuilder.Entity<DatasetAssignment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__dataset___3213E83FC4822148");

            entity.ToTable("dataset_assignments");

            entity.HasIndex(e => new { e.DatasetId, e.UserId }, "uq_dataset_user").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("assigned_at");
            entity.Property(e => e.DatasetId).HasColumnName("dataset_id");
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Dataset).WithMany(p => p.DatasetAssignments)
                .HasForeignKey(d => d.DatasetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__dataset_a__datas__5535A963");

            entity.HasOne(d => d.User).WithMany(p => p.DatasetAssignments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__dataset_a__user___5629CD9C");
        });

        modelBuilder.Entity<ExportItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__export_i__3213E83F752E2A88");

            entity.ToTable("export_items");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DataItemId).HasColumnName("data_item_id");
            entity.Property(e => e.ExportJobId).HasColumnName("export_job_id");
            entity.Property(e => e.FinalResultId).HasColumnName("final_result_id");

            entity.HasOne(d => d.DataItem).WithMany(p => p.ExportItems)
                .HasForeignKey(d => d.DataItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__export_it__data___7D439ABD");

            entity.HasOne(d => d.ExportJob).WithMany(p => p.ExportItems)
                .HasForeignKey(d => d.ExportJobId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__export_it__expor__7C4F7684");

            entity.HasOne(d => d.FinalResult).WithMany(p => p.ExportItems)
                .HasForeignKey(d => d.FinalResultId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__export_it__final__7E37BEF6");
        });

        modelBuilder.Entity<ExportJob>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__export_j__3213E83FB27DDC39");

            entity.ToTable("export_jobs");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DatasetId).HasColumnName("dataset_id");
            entity.Property(e => e.ExportFormat)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("export_format");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ExportJobs)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__export_jo__creat__797309D9");

            entity.HasOne(d => d.Dataset).WithMany(p => p.ExportJobs)
                .HasForeignKey(d => d.DatasetId)
                .HasConstraintName("FK__export_jo__datas__787EE5A0");

            entity.HasOne(d => d.Project).WithMany(p => p.ExportJobs)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__export_jo__proje__778AC167");
        });

        modelBuilder.Entity<FinalResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__final_re__3213E83FD2BB5DF5");

            entity.ToTable("final_results");

            entity.HasIndex(e => e.DataItemId, "UQ__final_re__3B99D4C7FDF04626").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnnotationId).HasColumnName("annotation_id");
            entity.Property(e => e.DataItemId).HasColumnName("data_item_id");
            entity.Property(e => e.DecidedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("decided_at");
            entity.Property(e => e.DecidedBy).HasColumnName("decided_by");

            entity.HasOne(d => d.Annotation).WithMany(p => p.FinalResults)
                .HasForeignKey(d => d.AnnotationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__final_res__annot__72C60C4A");

            entity.HasOne(d => d.DataItem).WithOne(p => p.FinalResult)
                .HasForeignKey<FinalResult>(d => d.DataItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__final_res__data___71D1E811");

            entity.HasOne(d => d.DecidedByNavigation).WithMany(p => p.FinalResults)
                .HasForeignKey(d => d.DecidedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__final_res__decid__73BA3083");
        });

        modelBuilder.Entity<Label>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__labels__3213E83F9EB1F1A0");

            entity.ToTable("labels");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK__labels__parent_i__60A75C0F");

            entity.HasOne(d => d.Project).WithMany(p => p.Labels)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__labels__project___5FB337D6");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__projects__3213E83F09CCC123");

            entity.ToTable("projects");

            entity.HasIndex(e => e.Name, "UQ__projects__72E12F1BDDDFBFC5").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("active")
                .HasColumnName("status");
        });

        modelBuilder.Entity<ProjectMember>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__project___3213E83FEBF953B3");

            entity.ToTable("project_members");

            entity.HasIndex(e => new { e.ProjectId, e.UserId }, "uq_project_member").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("joined_at");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.RoleInProject)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_in_project");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Project).WithMany(p => p.ProjectMembers)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__project_m__proje__44FF419A");

            entity.HasOne(d => d.User).WithMany(p => p.ProjectMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__project_m__user___45F365D3");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__reviews__3213E83F59BA5FB0");

            entity.ToTable("reviews");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnnotationId).HasColumnName("annotation_id");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.ReviewedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("reviewed_at");
            entity.Property(e => e.ReviewerId).HasColumnName("reviewer_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("status");

            entity.HasOne(d => d.Annotation).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.AnnotationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__reviews__annotat__6C190EBB");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ReviewerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__reviews__reviewe__6D0D32F4");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83FC2EB2A85");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E616464E0AFF1").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__users__F3DBC5721F4A2B3D").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .HasMaxLength(150)
                .HasColumnName("email");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("active")
                .HasColumnName("status");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}