// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class ActivityLog
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string Action { get; set; }

    public string EntityType { get; set; }

    public long? EntityId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}