// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class Annotation
{
    public long Id { get; set; }

    public long DataItemId { get; set; }

    public long UserId { get; set; }

    public string LabelValue { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual DataItem DataItem { get; set; }

    public virtual ICollection<FinalResult> FinalResults { get; set; } = new List<FinalResult>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual User User { get; set; }
}