// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class DatasetAssignment
{
    public long Id { get; set; }

    public long DatasetId { get; set; }

    public long UserId { get; set; }

    public string Role { get; set; }

    public DateTime? AssignedAt { get; set; }

    public virtual Dataset Dataset { get; set; }

    public virtual User User { get; set; }
}