// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class DataItemAssignment
{
    public long Id { get; set; }

    public long DataItemId { get; set; }

    public long UserId { get; set; }

    public string Status { get; set; }

    public DateTime? AssignedAt { get; set; }

    public virtual DataItem DataItem { get; set; }

    public virtual User User { get; set; }
}