// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class DataItem
{
    public long Id { get; set; }

    public long DatasetId { get; set; }

    public string Content { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Annotation> Annotations { get; set; } = new List<Annotation>();

    public virtual ICollection<DataItemAssignment> DataItemAssignments { get; set; } = new List<DataItemAssignment>();

    public virtual Dataset Dataset { get; set; }

    public virtual ICollection<ExportItem> ExportItems { get; set; } = new List<ExportItem>();

    public virtual FinalResult FinalResult { get; set; }
}