// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class ExportItem
{
    public long Id { get; set; }

    public long ExportJobId { get; set; }

    public long DataItemId { get; set; }

    public long FinalResultId { get; set; }

    public virtual DataItem DataItem { get; set; }

    public virtual ExportJob ExportJob { get; set; }

    public virtual FinalResult FinalResult { get; set; }
}