// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class ExportJob
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long? DatasetId { get; set; }

    public string ExportFormat { get; set; }

    public long CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Dataset Dataset { get; set; }

    public virtual ICollection<ExportItem> ExportItems { get; set; } = new List<ExportItem>();

    public virtual Project Project { get; set; }
}