// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class FinalResult
{
    public long Id { get; set; }

    public long DataItemId { get; set; }

    public long AnnotationId { get; set; }

    public long DecidedBy { get; set; }

    public DateTime? DecidedAt { get; set; }

    public virtual Annotation Annotation { get; set; }

    public virtual DataItem DataItem { get; set; }

    public virtual User DecidedByNavigation { get; set; }

    public virtual ICollection<ExportItem> ExportItems { get; set; } = new List<ExportItem>();
}