// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class Label
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public string Name { get; set; }

    public long? ParentId { get; set; }

    public virtual ICollection<Label> InverseParent { get; set; } = new List<Label>();

    public virtual Label Parent { get; set; }

    public virtual Project Project { get; set; }
}