// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class ProjectMember
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long UserId { get; set; }

    public string RoleInProject { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Project Project { get; set; }

    public virtual User User { get; set; }
}