// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class Review
{
    public long Id { get; set; }

    public long AnnotationId { get; set; }

    public long ReviewerId { get; set; }

    public string Status { get; set; }

    public string Comment { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public virtual Annotation Annotation { get; set; }

    public virtual User Reviewer { get; set; }
}