// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLabeling.Domain.Models;

public partial class User
{
    public long Id { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual ICollection<Annotation> Annotations { get; set; } = new List<Annotation>();

    public virtual ICollection<DataItemAssignment> DataItemAssignments { get; set; } = new List<DataItemAssignment>();

    public virtual ICollection<DatasetAssignment> DatasetAssignments { get; set; } = new List<DatasetAssignment>();

    public virtual ICollection<ExportJob> ExportJobs { get; set; } = new List<ExportJob>();

    public virtual ICollection<FinalResult> FinalResults { get; set; } = new List<FinalResult>();

    public virtual ICollection<ProjectMember> ProjectMembers { get; set; } = new List<ProjectMember>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}